public enum EventType {
  // Application State
  EVENT_APP_PAUSE,
  EVENT_APP_RESUME,
  
  // Entity Lifecycle
  EVENT_ENTITY_SPAWN_REQUEST,
  EVENT_ENTITY_DESTROY_REQUEST,
  EVENT_ENTITY_SELECTED,
  EVENT_ENTITY_DESELECTED,
  
  // Physics & Transform
  EVENT_PHYSICS_COLLISION_ENTER,
  EVENT_ENTITY_TRANSFORM_CHANGED,
  
  // Media & UI
  EVENT_AUDIO_PLAY_SAMPLE,
  EVENT_UI_WIDGET_CLICKED
}
